name: Python application test with Github Actions

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.1"

      - name: Install dependencies
        run: |
          make install
          python -m textblob.download_corpora

      # - name: Lint with flake8
      #   # run: make lint

      # - name: Test with pytest
      #   # run: make test

      # - name: Format code with Black
      #   # run: make format

      # - name: Build Docker container
      #   run: make build
